# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Try project euler
email: mptyomo＠gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chomo try log.
baseurl: "http://mogi.github.io/project_euler" # the subpath of your site, e.g. /blog
url: "http://mogi.github.io/project_euler" # the base hostname & protocol for your site
twitter_username: canaria_bot
github_username:  chomo

# Build settings
markdown: kramdown

gems:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed

theme: jekyll-theme-cayman